### ISSUE TITLE
Add support for HUBOT_GITHUB_API

### ISSUE THREAD

**Issue by mekwall** [markhuge/hubot-github-compare#10]
To support Github Enterprise installations.

**Comment by markhuge** [comment]
@mekwall Since this constructs a URL, wouldn't the option be for the enterprise appliance IP/host and not an API key? When you navigate to the URL, you're going in your browser and the authentication is going to be happening against whatever account you're logged into in the browser.

Let me know if I'm missing something, otherwise I'd be happy to add the host override for a github enterprise appliance.

**Comment by mekwall** [comment]
@markhuge Ah, you are confusing HUBOT_GITHUB_API with HUBOT_GITHUB_TOKEN. The HUBOT_GITHUB_API is used by several other scripts and is the full url to the API. E.g. `https://github.myhost.com/api/v3`.
